### PR TITLE
Add script to create data split for corpus with specific number of words

### PR DESCRIPTION
**Pull request by cbrochtrup**
This PR adds script `split_corpus.py` which creates data splits for a corpus with close to a defined number of words. This is useful to ensure WER calculations for dev and tests data are accurate while also preserving as much data for training as possible.

A script to test asrtoolkit using the docker image was also added.

### CODE REVIEW

**Comment by cbrochtrup** [comment]
> How many of the functions in split_corpus should be members of exemplar or corpus classes?

`count_words` could be part of exemplars while `generate_data_split` and `make_data_split` could be members of `corpus`. I originally had them there but moved them because I was worried about bloat for some reason. Are you thinking this would replace the splitting in scripts that prepare corpora for training? Then I could add these functions to the appropriate classes.

**Comment by cbrochtrup** [comment]
Unless someone has an idea how to reduce the number of inputs to a `Fire` CLI without affecting readability I'll ignore the code climate issue.

**Comment by sv-github** [comment]
> Unless someone has an idea how to reduce the number of inputs to a `Fire` CLI without affecting readability I'll ignore the code climate issue.

the arguments are keyworded which adds readability :+1: 
so having 6 args isn't that concerning

**Comment by cbrochtrup** [comment]
Good call on the cyclomatic complexity, I had some methods that made that easy. I'll merge once I get it to pass CI.

**Pull request merged**
